/**
 * Instrument seed data — seeded to MongoDB on first startup.
 * Prices are NOT stored here (fetched live from providers).
 * Only metadata that is stable.
 */
export const INSTRUMENT_SEED = [
  {
    id: 'BTCUSDT',
    symbol: 'BTC/USDT',
    name: 'Bitcoin / Tether',
    assetClass: 'crypto',
    baseCurrency: 'BTC',
    quoteCurrency: 'USDT',
    pipSize: 1.0,
    tickSize: 0.01,
    defaultTimeframe: '15M',
    provider: 'binance',
    isActive: true,
  },
  {
    id: 'ETHUSDT',
    symbol: 'ETH/USDT',
    name: 'Ethereum / Tether',
    assetClass: 'crypto',
    baseCurrency: 'ETH',
    quoteCurrency: 'USDT',
    pipSize: 0.1,
    tickSize: 0.01,
    defaultTimeframe: '15M',
    provider: 'binance',
    isActive: true,
  },
  {
    id: 'SOLUSDT',
    symbol: 'SOL/USDT',
    name: 'Solana / Tether',
    assetClass: 'crypto',
    baseCurrency: 'SOL',
    quoteCurrency: 'USDT',
    pipSize: 0.01,
    tickSize: 0.001,
    defaultTimeframe: '15M',
    provider: 'binance',
    isActive: true,
  },
  {
    id: 'EURUSD',
    symbol: 'EUR/USD',
    name: 'Euro / US Dollar',
    assetClass: 'forex',
    baseCurrency: 'EUR',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    defaultTimeframe: '15M',
    provider: 'yahoo',
    isActive: true,
  },
  {
    id: 'GBPUSD',
    symbol: 'GBP/USD',
    name: 'British Pound / US Dollar',
    assetClass: 'forex',
    baseCurrency: 'GBP',
    quoteCurrency: 'USD',
    pipSize: 0.0001,
    tickSize: 0.00001,
    defaultTimeframe: '15M',
    provider: 'yahoo',
    isActive: true,
  },
  {
    id: 'USDJPY',
    symbol: 'USD/JPY',
    name: 'US Dollar / Japanese Yen',
    assetClass: 'forex',
    baseCurrency: 'USD',
    quoteCurrency: 'JPY',
    pipSize: 0.01,
    tickSize: 0.001,
    defaultTimeframe: '15M',
    provider: 'yahoo',
    isActive: true,
  },
  {
    id: 'XAUUSD',
    symbol: 'XAU/USD',
    name: 'Gold / US Dollar',
    assetClass: 'commodities',
    baseCurrency: 'XAU',
    quoteCurrency: 'USD',
    pipSize: 0.1,
    tickSize: 0.01,
    defaultTimeframe: '15M',
    provider: 'yahoo',
    isActive: true,
  },
  {
    id: 'US500',
    symbol: 'S&P 500',
    name: 'S&P 500 Index',
    assetClass: 'indices',
    baseCurrency: 'USD',
    quoteCurrency: 'USD',
    pipSize: 0.25,
    tickSize: 0.01,
    defaultTimeframe: '15M',
    provider: 'yahoo',
    isActive: true,
  },
  {
    id: 'NAS100',
    symbol: 'NAS100',
    name: 'Nasdaq 100 Index',
    assetClass: 'indices',
    baseCurrency: 'USD',
    quoteCurrency: 'USD',
    pipSize: 0.25,
    tickSize: 0.01,
    defaultTimeframe: '15M',
    provider: 'yahoo',
    isActive: true,
  },
];
